### ISSUE TITLE
no dark mode

### ISSUE THREAD

**Issue by moxv** [namwa/minimalist-theme#1]
The theme is great, not adapted to the dark mode

code bug
![_20230417103645.png](https://www.z4a.net/images/2023/04/17/_20230417103645.png)

**Comment by namwa** [comment]
Thanks. Do you mean dark mode for the whole theme or just for the code blocks ?

**Comment by moxv** [comment]
theme dark

**Comment by namwa** [comment]
This theme doesn't intend to be used in dark mode, as it's a minimalist style. I'll keep that in mind for a future theme.
